### ISSUE TITLE
Doesn't scrobble from YouTube on Safari 11.0.3

### ISSUE THREAD

**Issue by xguidox** [cgravolet/scroblr#132]
Even if AdGuard is turned off.

**Comment by korzo** [comment]
Same problem on Chrome. As far as I can tell, problem is [here](https://github.com/cgravolet/scroblr/blob/master/src/js/plugins/youtube.js#L12)

**Comment by goodevilgenius** [comment]
@cgravolet, I have a PR to fix this: #134
