### ISSUE TITLE
Does not work on Spotify Web Client

### ISSUE THREAD

**Issue by serv** [cgravolet/scroblr#137]
Repro

1. Go to spotify.com
2. Sign in
3. Open web client: https://open.spotify.com
4. Play a track. Notice that this isn't being scrobbled by scroblr.

Acceptance

Scroblr should scrobble tracks played on open.spotify.com

**Comment by grantbacon** [comment]
I'd be happy to write out a plugin for this. Especially since its a single page app with a consistent player always visible, makes it really easy. 😄

**Comment by cgravolet** [comment]
I believe Spotify supports native scrobbling, which is why the feature was removed from scroblr. Native scrobbling is almost always better than from an extension.

**Comment by hans-juergen** [comment]
No, Spotify has disabled their internal scrobbling in all of their apps including their web player a long time ago. But Last.fm offers an own Spotify scrobbling feature now which you can enable on your Last.fm applications settings page:

https://www.last.fm/settings/applications

Furthermore the other Last.fm web scrobbler browser extension for Chrome, Opera and Firefox still supports Spotify scrobbling as well:

https://chrome.google.com/webstore/detail/lastfm-scrobbler/hhinaapppaileiechjoiifaancjggfjm
