### ISSUE TITLE
Rhapsody plugin not working properly after update to web player

### ISSUE THREAD

**Issue by serv** [cgravolet/scroblr#57]
http://beta.rhapsody.com/ is in open beta. Let's add support for it on scroblr.

**Comment by cgravolet** [comment]
I've gotten a few comments on twitter about the Rhapsody plugin not working anymore after an update to the Rhapsody site. I'm assuming they are now out of beta, so this is now a bug instead of an enhancement.

**Comment by serv** [comment]
Ya, Rhapsody web player is out of beta now.

Do you think the fix pretty much comes down to changing the selector for grabbing the right info for the track here?
https://github.com/cgravolet/scroblr/blob/master/src/js/plugins/rhapsody.js#L18

**Comment by cgravolet** [comment]
Yea, want to take a stab at it? I don't have a rhapsody account, otherwise I would have fixed this a while ago.

**Comment by serv** [comment]
@cgravolet just made a PR for the bug.
What's the best way to reach you in case I need to contact you?

**Comment by cgravolet** [comment]
Thanks! I just merged it in and pushed a release to the chrome store.
