### ISSUE TITLE
Soundcloud issues

### ISSUE THREAD

**Issue by bolatovumar** [cgravolet/scroblr#68]
* Scrobbling Soundcloud sets doesn't work at all (you can see the problem reported [here](https://chrome.google.com/webstore/detail/scroblr/mflbcmpjneookibbaeopkfcnegknkgog/support) numerous times)
* Scrobbling from playlists also doesn't work (same for reposted playlists)
* Wrong artist and track data is scrobbled if the artist name and account name differ
* Wrong track title is scrobbled if an artist specifies his name in the title of the song

Essentially, Soundcloud scrobbling will work correctly only in the simplest of cases (i.e, the track being scrobbled is not in a playlist or a set, it has not been reposted by someone and the artist's name perfectly matches the account username which is oftentimes not the case).

**Comment by Yoshi8765** [comment]
Seems like scrobbling is broken again as of now (May 9th). A song will appear as "Now Playing in last.fm" but will disappear after a few seconds.

**Comment by Robin-des-Bois** [comment]
Any news on this fron? Looks like soundcloud support was dropped completely?
