### ISSUE TITLE
foobar feature

### ISSUE THREAD

**Issue by TheSpaceArmy** [cgravolet/scroblr#89]
hope you peole add a feature for foobar

**Comment by cincodenada** [comment]
Foobar is a desktop audio player, this is a browser extension for scrobbling from web-based music players, so you seem to be in the wrong place.

If you're still looking for a scrobbler for Foobar2000, there seems to be a scrobbler component, but it seems pretty old and I can't vouch for anything about it: www.foobar2000.org/components/view/foo_audioscrobbler
