### ISSUE TITLE
Not working anymore?

### ISSUE THREAD

**Issue by diniscorreia** [cgravolet/scroblr#95]
Just installed successfully on Chrome and Safari - but no tracks are being scrobbled. Trying with SoundCloud (Safari does show a notification saying a song is playing).

**Comment by Nicholi** [comment]
I noticed it shows "scrobbling now" on last.fm recent tracks. But it never actually scrobbles the play...it's weird. Something about duration/elapsed being passed maybe?

**Comment by eugenet8k** [comment]
It doesn't work for me in Safari 9.0.2.
It doesn't scrobble any tracks from bandcamp and I don't even see the way how to setup my last.fm account. In Safari Preferences / Extensions / scroblr doesn't have any settings :-1:

**Comment by grantbacon** [comment]
It seems the soundcloud plugin is not working properly. Though, I am still able to scrobble from other websites (I tried google play music and SomaFM)

**Comment by cgravolet** [comment]
@eugenet8k Click the scroblr icon in the toolbar to authenticate with Last.fm

**Comment by cgravolet** [comment]
@diniscorreia @grantbacon I just released a possible fix for the SoundCloud issue, looks like SoundCloud made minor changes to the HTML structure that defines the duration/elapsed time. Can you test it out if you get a chance, scroblr v2.2.1
