### ISSUE TITLE
Safari. Authorizing didn't work

### ISSUE THREAD

**Issue by DmitrySharikov** [cgravolet/scroblr#96]
I just tried authorize extension and got this:
![failed to open page 2015-09-01 19-52-59](https://cloud.githubusercontent.com/assets/6432274/9610574/19020984-50e3-11e5-80fc-f75e79f0e1dc.png)

Hope, you know how to fix it :)

p.s. thx for extension

**Comment by cgravolet** [comment]
I just uploaded a possible fix, can you delete and then reinstall the extension and try again? http://scroblr.fm
